// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import AppWalletProvider from "@/component/AppWalletProvider";
// import { SessionProvider } from "next-auth/react"

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AppWalletProvider>
//           <SessionProvider>
//             {children}
//           </SessionProvider>
//         </AppWalletProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "@/component/AppWalletProvider";
import Providers from "@/component/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>  {/* Use the new Providers component */}
          <AppWalletProvider>
            {children}
          </AppWalletProvider>
        </Providers>
      </body>
    </html>
  );
}