// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import AppWalletProvider from "@/component/AppWalletProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <AppWalletProvider>
//       {children}
//       </AppWalletProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "@/component/AppWalletProvider";
import { DynamicContextProvider, DynamicWidget } from '@dynamic-labs/sdk-react-core';
import { SolanaWalletConnectors } from "@dynamic-labs/solana";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: '364b8543-a4b7-4a37-a301-20f6f687364d',
            walletConnectors: [SolanaWalletConnectors],
          }}
        >
          {/* <AppWalletProvider> */}
            {/* <DynamicWidget /> */}
            {children}
          {/* </AppWalletProvider> */}
        </DynamicContextProvider>
      </body>
    </html>
  );
}